MIN_X_CORD = 10
MAX_X_CORD = 28

MIN_Y_CORD = 10
MAX_Y_CORD = 26

HEIGHT_MIN_VALUE = -16384
HEIGHT_MAX_VALUE = 16376

# 1 << 8
GEO_REGION_SIZE = 256

# =================== #
# L2Script protection #

# Will bruteforce all bind ip addresses
# Can going up to 10 minutes
SHUFFLE_L2S_CRYPT = true
# If you have a bind ip you can try to de-crypt
L2S_BIND_IP_ADDRESS = 127.0.0.1

# L2Script protection #
# =================== #

# Available formats:
# L2J, CONV_DAT, PATH_TXT, L2D, L2G, RP, L2M, L2S (additional actions required)
READ_FORMAT = PATH_TXT
# L2J, CONV_DAT, L2G
# Can assign multiple values when split by ";"
SAVE_FORMAT = l2j;conv_dat

# Will optimize a Complex block into Flat block
RUN_OPTIMIZATION = true

# Height limit between cells in current block, which can be optimized into flat
# Off-like = 16
# Java-like = 32
HEIGH_DIFF_FOR_OPTIMIZATION = 16

# Heigh limit between cells in surrounding blocks, which can be optimized into flat
# Off-like = 16
# Java-like = 32
HEIGHT_DIFF_IN_SURROUNDED_BLOCK = 16

# Height diff of cells between current block and surrounding blocks
# Value, on which character cannot move from this block to other (like fall from wall)
WALL_HEIGH_FOR_OPTIMIZATION = 64

# For optimize blocks we using 3 methods:
# 1. Check is all nswe and minimal and maximal height is the same
# 2. Check if range between minimal and maximal height in all cells is in range of HEIGH_DIFF_FOR_OPTIMIZATION
# 3. Check if if average range in current block is in range of HEIGH_DIFF_FOR_OPTIMIZATION in surrounded cells of current block
CAN_OPTIMIZE_BLOCK_ON_EDGE = true

# Will logging if flat block is not cannot be a flat, and should be a complex
LOG_FLAT_BLOCK_ISSUE_ON_OPTIMIZATION = false